from .falcon import FalconJointLinker, FalconDBpediaJointLinker, FalconWikidataJointLinker
from .earl import EARLJointLinker
from .spacy_ann import DBpediaSpacyANNJointLinker, WikidataSpacyANNJointLinker
from .es_based import ESFalconDBpediaJointLinker, ESFalconWikidataJointLinker
from .es_based import ESEarlDBpediaJointLinker, ESEarlWikidataJointLinker, ESTagMeDBpediaJointLinker
from .es_based import ESTagMeWikidataJointLinker
from .orkg_ann import ORKGSpacyANNLinker
